---
title: "Modeller"
output: html_notebook
---

```{r setup, echo=FALSE, message=FALSE}
suppressPackageStartupMessages({
  library(tidyverse)
  library(lubridate)
  library(modelr)
  library(broom)
  library(lmtest)
  library(sandwich)
  library(viridis)
})
# Chunk opsjonene satt nedenfor er for mitt bruk
# Gjør at jeg kan holde noen av kortene skjult ;-)
knitr::opts_chunk$set(echo = FALSE, include = FALSE)
```


```{r henter pm2 filen}
pm2 <- read_csv("data/pm2.csv", show_col_types = FALSE)
```


```{r mutatet og string}
pm2 <- pm2 %>% 
  mutate(
    fnr = str_sub(knr, 1,2),
    aar_f = str_sub(aar)
  )
```


```{r ser paa head}
head(pm2)
```


```{r parsefactor}
pm2 %>% 
  mutate(
    fnr = parse_factor(fnr, levels = fnr),
    aar_f = parse_factor(aar_f, levels = aar_f)
  )
```


```{r mutate og select}
pm2 <- pm2 %>% 
  mutate(
    Trade_pc_100K = Trade_p/100000
  ) 
```

```{r head}
head(pm2, n = 4)
```

# Modell

### i

```{r}
mod1 <- 'pm2 ~ aar_f + Total_ya_p + inc_k1 + inc_k5 + uni_k_mf + uni_l_mf + Trade_pc_100K'
```


```{r}
lm1 <- lm(mod1, data = pm2, subset = complete.cases(pm2))
```

```{r}
summary(lm1)
```

### ii

### Legge til residualene fr aden linære modellen til datasettet pm2

```{r}
pm2 %>% 
  add_residuals(lm1)

head(pm2, n=4)
```

## Forklaring til modell

### i 
Derom året er 2009 øker pm2 med 104, 2010 med 908 osv. og til slutt i 2017 øker pm2 med 5146. 
År 2009 er ikke signifikant, men fra år 2010-2017 er koeffisientene signifikant på 0,1% nivå. Man ser en økning fra år til år i koeffisientene. 

### ii 

Vet ikke.

## Heteroskedastisitet 
