---
title: "hent-ssb-data"
author:
- "Kine Måkestad"
- "Susann Sivertsen"
fontsize: 12pt
linestrech: 1.5
output:
  pdf_document: default
  html_document:
    df_print: paged
  word_document: default
lang: no-NB
---

## Assignment 4: SSB data

## Data hentet
Data sist hentet 28. desember 2021.

```{r}
knitr::opts_chunk$set(eval = FALSE)
```


```{r setup, include=FALSE}
suppressPackageStartupMessages({
  library(PxWebApiData)
  library(tidyverse)
  library(lubridate)
})
knitr::opts_chunk$set(echo = FALSE, include = FALSE)
```

Laster inn data for alle kommunene, og disse ligger i "knr.Rdata". 

```{r loaderindata}
load("knr.Rdata")
```


```{r gjennomsnittligkvmpris}
pm2_raw <- ApiData(
  urlToData = "06035",
  Region = knr,
  ContentsCode = "KvPris",
  Boligtype = "01",
  Tid = c(as.character(2002:2017))
)
```


```{r datasett}
pm2 <- pm2_raw$dataset %>% 
  tibble() %>% 
  select(-Boligtype, -ContentsCode) %>% 
  rename(
    knr = Region,
    aar = Tid,
    pm2 = value
  )
head(pm2)
```


```{r endrernavntildesc}
names(pm2_raw)[[1]] <- "desc"
```



```{r knavn}
pm2 <- pm2 %>% 
  mutate(
    knavn = pm2_raw$desc$region
  )
```



```{r}
load("test_string_tib.Rdata")

# Legg inn regex mønster
moenster <- '\\s+\\(\\d*[19-]\\d*[2019]\\)\\s*$'
```



```{r}
test_string_tib %>% 
  mutate(
    knavn = str_replace(knavn, moenster, "")
  )
```

## NA-verdier i pm2

```{r}
df_pm2 <- pm2 %>% 
  map_df(is.na) %>% 
  map_df(sum)
```


```{r}
df_pm2 %>% 
  table()
```


## Complete.cases

```{r}

```



 





